Repository Livinglist/Hacki, pull requests merged in 2022-06, with the labels that each got.

#37 Add capitalization hinting to text fields
  lib/screens/story/widgets/reply_box.dart
  lib/screens/submit/submit_screen.dart
Labels: enhancement

#47 v0.2.17
  fastlane/metadata/android/en-US/changelogs/56.txt
  ios/Runner.xcodeproj/project.pbxproj
  lib/cubits/comments/comments_cubit.dart
  lib/cubits/cubits.dart
  lib/cubits/user/user_cubit.dart
  lib/cubits/user/user_state.dart
  lib/models/buildable_comment.dart
  lib/models/models.dart
  lib/models/user.dart
  lib/screens/home_screen.dart
  lib/screens/profile/profile_screen.dart
  lib/screens/story/story_screen.dart
  lib/screens/story/widgets/fav_icon_button.dart
  lib/screens/story/widgets/link_icon_button.dart
  lib/screens/story/widgets/pin_icon_button.dart
  lib/screens/widgets/comment_tile.dart
  lib/screens/widgets/items_list_view.dart
  pubspec.yaml
Labels: do not merge

#48 allow plaintext http connections
  android/app/src/main/AndroidManifest.xml
Labels: v0.2.18
